### ISSUE TITLE
!help not working with AttributeError:'str' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by when-idle** [UofE-Gaming-Society/DiscordGameTracker#9]
`!help` command not working, rest is working fine.
 
Error as shown:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/me/code/DiscordGameTracker/.venv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/me/code/DiscordGameTracker/gametracker.py", line 166, in on_message
    await message.channel.send(embed=output)
  File "/home/me/code/DiscordGameTracker/.venv/lib/python3.9/site-packages/discord/abc.py", line 1016, in send
    embed = embed.to_dict()
AttributeError: 'str' object has no attribute 'to_dict'
```

**Comment by when-idle** [comment]
#10

**Comment by GreigHuth** [comment]
Pull request merged
